blank_issues_enabled: false
contact_links:
  - name: â“è³ªå•ã¯ã“ã¡ã‚‰ / Questions Here
    url: https://github.com/y-daiki-nakamura/docusaurus-fast/discussions
    about: è³ªå•ã‚„ç›¸è«‡ã¯ã€Discussions ã‚»ã‚¯ã‚·ãƒ§ãƒ³ã‚’ã”åˆ©ç”¨ãã ã•ã„ã€‚ / Please use the Discussions section for questions or general inquiries.
  - name: ğŸ’¡æ©Ÿèƒ½è¦æœ›ï¼ˆã‚¢ã‚¤ãƒ‡ã‚¢ï¼‰ã¯ã“ã¡ã‚‰ / Feature Request Here
    url: https://github.com/y-daiki-nakamura/docusaurus-fast/discussions
    about: æ©Ÿèƒ½è¦æœ›ï¼ˆã‚¢ã‚¤ãƒ‡ã‚¢ï¼‰ã¯ã€Discussions ã‚»ã‚¯ã‚·ãƒ§ãƒ³ã‚’ã”åˆ©ç”¨ãã ã•ã„ã€‚ / Please use the Discussions section for feature requests or ideas.
